name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-18.04, ubuntu-20.04]
        python-version: [3.6, 3.7, 3.8, 3.9.0-rc.1, pypy3]
        target-ros2-distro: [foxy]

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: ros-tooling/setup-ros@master
      - run: colcon version-check
      - run: pip3 list
      - uses: actions/checkout@v2
        with:
          path: colcon-cmake-src
      - run: >
          pip3 install --user --upgrade --upgrade-strategy eager
          ${{ github.workspace }}/colcon-cmake-src
          colcon-common-extensions
          catkin-pkg
          rosdep
      - run: colcon version-check
      - run: pip3 list
      - name: Install and test ROS
        uses: ros-tooling/action-ros-ci@master
        with:
          package-name: rclcpp test_rclcpp
          target-ros2-distro: ${{ matrix.target-ros2-distro }}
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/${{ matrix.target-ros2-distro }}/ros2.repos
